//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mebel_centr.Pages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employers()
        {
            this.sotrudnik = new HashSet<sotrudnik>();
        }
    
        public int id_employers { get; set; }
        public string imya { get; set; }
        public string familiya { get; set; }
        public string otchestvo { get; set; }
        public int id_roli { get; set; }
    
        public virtual roli roli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sotrudnik> sotrudnik { get; set; }
        public virtual Users Users { get; set; }
    }
}
