//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entitiesq : DbContext
    {
        public Entitiesq()
            : base("name=Entitiesq")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employers> employers { get; set; }
        public virtual DbSet<kategory_produkt> kategory_produkt { get; set; }
        public virtual DbSet<klient> klient { get; set; }
        public virtual DbSet<otzivi> otzivi { get; set; }
        public virtual DbSet<postavshiki> postavshiki { get; set; }
        public virtual DbSet<produkt> produkt { get; set; }
        public virtual DbSet<roli> roli { get; set; }
        public virtual DbSet<sotrudnik> sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
    }
}
