//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produkt()
        {
            this.kategory_produkt = new HashSet<kategory_produkt>();
            this.otzivi = new HashSet<otzivi>();
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int Id_produkt { get; set; }
        public string nazvanie { get; set; }
        public decimal cena { get; set; }
        public string opisanie { get; set; }
        public string kategory { get; set; }
        public bool nalichie { get; set; }
        public int id_postavshika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kategory_produkt> kategory_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<otzivi> otzivi { get; set; }
        public virtual postavshiki postavshiki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
