//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sotrudnik()
        {
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int id_sotrudnika { get; set; }
        public string imya { get; set; }
        public string familiya { get; set; }
        public string otchestvo { get; set; }
        public string dolzhnost { get; set; }
        public decimal zarplata { get; set; }
        public System.DateTime data_priema { get; set; }
        public int id_employers { get; set; }
        public string id_zakaz { get; set; }
    
        public virtual employers employers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
