//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int id_zakaza { get; set; }
        public int id_produkta { get; set; }
        public int kolvo { get; set; }
        public decimal obsh_summa { get; set; }
        public System.DateTime data_zakaza { get; set; }
        public string status { get; set; }
        public int id_sotrudnik { get; set; }
    
        public virtual produkt produkt { get; set; }
        public virtual sotrudnik sotrudnik { get; set; }
    }
}
